name: ESLint

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  eslint:
    # Name the Job
    name: Run ESLint
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: eslint

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        uses: bradennapier/eslint-plus-action@v3.4.2
        with:
          issueSummary: true
          issueSummaryType: compact
          issueSummaryMethod: edit
          issueSummaryOnlyOnEvent: false
          annotateWarnings: true
          reportSuggestions: true
          reportIgnoredFiles: false
          reportWarningsAsErrors: false
